### ISSUE TITLE
Cadastro de atendentes

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/chamados#1]
## Requisito 1 (OK)
Login/Validação será feita através LDAP

## Requisito 2 (OK)
Possibilidade de filtrar pelo setor e pesquisar pelo nome do atendente

## Requisito 3 (OK - Implementar na issue #14)
Qualquer tipo de alteração na lotação do atendente deve refletir automaticamente no sistema. (relacionada com issue #14)

## Requisito 4 (OK - Implementar na issue #14)
Caso haja alteração na lotação do atendente, todos os chamados abertos relacionados a ele devem ser colocados novamente na fila de chamados abertos.

## Requisito 5 (OK - Campo para isso já relacionado)
Cada setor deverá ter um admin que será buscado pelo LDAP/Elotech* para receber futuras mensagens do sistema.

## Requisito 6 (OK)
O LDAP deverá permitir acesso a todos os campos necessários ao cadastro.

## Relacionamento entre campos LDAP/Django
* uid : username
* givenName : first_name
* sn : last_name
* mail : email
* employeeNumber : matricula
* departmentNumber : lotado
* employeeType : chefia

### Pendências
<s>1. Definir com Tora qual campo do LDAP irá conter o setor em que o usuário está lotado.</s>
Definido campo departmentNumber
<s>2. Definir estrutura/funcionamento da sincronia de informações entre o sistema da elotech/LDAP</s>
Criada issue #14 para contemplar essa necessidade.
<s>3. Definir estrutura e issues para "espelho" de informações do organograma cadastrado no sistema Elotech</s>
Criada issue #14 para contemplar essa necessidade.
<s>4. Definir com Tora se o acesso ao LDAP para leitura das informações será anônimo ou se criaremos um usuário específico para isso. De qualquer maneira que for acessado, deve ser permitido o acesso à todas as informações necessárias.</s>
Definido acesso anônimo. Problema de permissões na verdade era o servidor de LDAP que estava sendo acessado.
<s>5. Sobrescrever o método de gravar dados do usuário no BD para que o campo "MEMBRO DA EQUIPE" fique como True</s>
Não é necessário. is_staff é setado True apenas para usuários que podem acessar o admin.

**Comment by aleodoni** [comment]
@fderosso, dê uma olhada nos requisitos, se precisa de mais alguma coisa.
Pretendo começar por esta issue; fico no aguardo do OK para dar o pontapé.

**Comment by fderosso** [comment]
É isso aí, pode começar, só fiquei em dúvida no requisito 4, qual o esquema do LDAP alterar a lotação do atendente no sistema? Isso é bom pq tem outros sistemas que dependem dessa funcionalidade tb.

**Comment by aleodoni** [comment]
@fderosso, imagino que essa alteração será feita no sistema de RH e deverá ser posteriormente replicada no LDAP. O sistema de chamados apenas faria a verificação das informações.

**Comment by aleodoni** [comment]
Vou começar a desenvolver então, escrevendo os testes baseados nos requisitos acima e depois escrevendo as camadas.

**Comment by edersoncosta** [comment]
Pode começar, mas acredito que só basta o Tora ver a parte dele.

**Comment by aleodoni** [comment]
Vou conversar com o Tora pra ver se os requisitos contemplam o que ele precisa e aí começo.

**Comment by aleodoni** [comment]
Conversei com o Tora e fechamos os requisitos dessa issue. Vou começar a desenvolver.

**Comment by aleodoni** [comment]
Usando o https://github.com/etianen/django-python3-ldap.
Com isso, toda vez que um usuário se loga como sucesso no sistema (via LDAP é claro), suas informações são atualizadas no model user do django.

**Comment by aleodoni** [comment]
Vou conversar com o Diego para ver como funciona na elotech o cadastro de lotações para ver como procedemos no desenvolvimento.

**Comment by aleodoni** [comment]
A princípio, vou deixar esse controle através do admin mesmo; caso haja necessidade de criar um controle específico fora dos padrões do admin, criaremos outra issue.
Como não houve manifestação em relação aos campos e requisitos, implementei desta maneira e estou fechando a issue.
