### ISSUE TITLE
Erro 500 ao fazer login

### ISSUE THREAD

**Issue by Angelin01** [CMCuritiba/chamados#106]
Em anexo uma print do erro e um .html da página gerada. A senha foi censurada por motivos óbvios.

![screenshot-2018-3-13 httperror at autentica valida-usuario](https://user-images.githubusercontent.com/17818024/37341507-5f659fc2-26a0-11e8-9a30-9aba5afaa0ca.png)

[HTTPError at _autentica_valida-usuario_.txt](https://github.com/CMCuritiba/chamados/files/1806815/HTTPError.at._autentica_valida-usuario_.txt)

Arquivo .html foi renomeado para .txt porque GitHub não gosta de htmls.

**Comment by aleodoni** [comment]
Ainda não foi definido se os estagiários poderão acessar o sistema de chamados. Esse erro ocorre em razão do cadastro LDAP/Sistema Elotech. Vou fechar essa issue até definirmos isto e se for o caso reabrir a mesma.
