### ISSUE TITLE
Anexos de arquivos

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/chamados#115]
@brunosoli Favor revisar os requisitos e sugerir alterações

**Requisito 1**
Usuário pode anexar até 3 arquivos

**Requisito 2**
Qualquer tipo de imagem:   ["jpg", "png", "gif", "jpeg"]

**Requisito 3**
Tamanho máximo por imagem 5 Mb

**Comment by aleodoni** [comment]
Pra gente não criar uma lista gigante de imagens no código, sugestão : ["jpg", "png", "gif", "jpeg"]

**Comment by aleodoni** [comment]
Já implementado para as issues acima. Quando quiserem, me avise que faço o merge.
