### ISSUE TITLE
Visualização das respostas

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#133]
Sugestão de melhoria na visualização das respostas de um chamado.

Hoje elas são visualizadas numa aba, e se fizéssemos algo tipo:
- Uma indicação na aba com o número de respostas cadastradas (no formato a aba "Issues" aqui do github) ou;
- Visualizado na própria aba do chamado, abaixo dos seus dados, no formato de fórum.

**Comment by aleodoni** [comment]
Legal a sugestão. De início vou fazer o esquema da indicação de respostas tipo pill/badges (https://getbootstrap.com/docs/4.0/components/badge/). Depois implementamos o esquema da visualização tipo forum.
