### ISSUE TITLE
Sincronia Elotech LDAP

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/chamados#14]
## Descrição
Fazer a sincronia dos campos LDAP utilizando as views da Elotech.
A princípio, deverão ser sincronizados com o LDAP as seguintes informações referentes aos funcionários : 
1. Número de matrícula do servidor
2. Setor em que o servidor está lotado
3. Informação referente à disponibilidade do servidor. Se ele está de férias, de licença, de atestado,etc. deve ficar como indisponível. Caso contrário ficará como disponível.

Existe a view V_SETOR que foi criada especificamente para a TI da CMC, e que possui as informações referentes à lotação dos funcionários.
De acordo com o pessoal da Elotech, existem mais duas views são usadas pelo sistema e fornecem as outras informações desejadas. 
Deverá ser feita análise para verificar se serão utilizadas as views (do sistema) ou se serão criadas novas views específicas para a TI da CMC.

## Requisito 1
Esta rotina deverá ser executada em intervalos que deverão ser definidos pelos responsáveis.

## Requisito 2
A rotina deverá acessar o LDAP para poder ler e gravar as informações necessárias.

## Requisito 3
Em caso de erro, a rotina deverá avisar o responsável do acontecido.

**Comment by fderosso** [comment]
Existe no banco da elotech uma tabela chamada rhmovimentacaopessoal que é pai das tabelas rhmovimentacao*, aonde tem a matricula, o cargo(codigo) da pessoa,  iniciovigencia e finalvigencia que podem ser usadas para saber a disponibilidade da pessoa. Posso criar um usuário no banco deles para acessar essas informações.

**Comment by aleodoni** [comment]
Conversei com o @fderosso, vou fechar essa issue e criar um repositório novo para esse projeto.
