### ISSUE TITLE
Criar banco de dados Banco Dados 

### ISSUE THREAD

**Issue by edersoncosta** [CMCuritiba/chamados#149]
Solicito @brunosoli  que se crie Bando de Dados para o Sistema de Chamados no servidor de Produção.

Fornecer:

- Conexão
- Usuário
- Senha

O usuário deve ter permissão para criar tabelas.
Para conhecimento marco @diemello @aleodoni

**Comment by brunosoli** [comment]
**Apesar** de termos combinado anteriormente de esperar para não prejudicar o sistema em produção, visto que o @aleodoni está trabalhando **sozinho** nos softwares de chamados e de calendário e que foi dada prioridade para o calendário, o banco em produção foi desativado e um novo banco foi criado (mesmo nome e usuário).

Portanto, o sistema de chamados em produção não está funcionando.
