### ISSUE TITLE
Exibir setor de origem do chamado

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#159]
Sugestão: na tela de "Informações do chamado" exibir também o setor da pessoa que abriu o chamado.

**Comment by aleodoni** [comment]
@brunosoli, verifique em https://chamados-staging.cmc.pr.gov.br/. Vou fechar a issue. Caso necessário, reabrir.

**Comment by brunosoli** [comment]
Em "Atendimento", na tela de "Informações do chamado" o setor sendo exibido é o setor de destino do chamado, não o setor de quem o abriu.

**Comment by aleodoni** [comment]
@brunosoli, @diemello Versão com a alteração solicitada está em staging. Quando puderem, testem e me dê o OK para colocar em produção.
