### ISSUE TITLE
Adicionar o campo "outros" na comboBox Serviço

### ISSUE THREAD

**Issue by Angelin01** [CMCuritiba/chamados#161]
A combo box "Servi**c**o" deve ter um campo "outros", já que nem sempre todas as situações imaginadas em relação a tal serviço estarão disponíveis ali.

**Comment by aleodoni** [comment]
Isso deve ser feito via sistema, no cadastro de serviços. Não é uma issue e sim manutenção na lista de itens, por isso estou fechando a mesma.
