### ISSUE TITLE
Incluir hora no campo "Data de abertura" dentro do chamado

### ISSUE THREAD

**Issue by Angelin01** [CMCuritiba/chamados#162]
Atualmente o campo "Data de abertura" dentro do chamado mostra apenas o dia. É interesse ter a hora disponível, pois é grande a diferença entre um chamado aberto as 8:00 e as 16:00.

**Comment by aleodoni** [comment]
@Angelin01 , verifique em : https://chamados-staging.cmc.pr.gov.br.
Vou fechar a issue. Caso necessário, abrir outra.

**Comment by Angelin01** [comment]
A adição do horário no campo aberto foi útil, porém ainda não é incluída na parte de "atendimento", na parte inferior da página. Agradeceria se fosse incluído também nessa seção.

![image](https://user-images.githubusercontent.com/17818024/48769569-2175e900-eca3-11e8-8b48-46d2ea70bb99.png)

**Comment by aleodoni** [comment]
Corrigido. Será atualizado no próximo deploy
