### ISSUE TITLE
Atualizar labels para usar cedilha e acentos

### ISSUE THREAD

**Issue by Angelin01** [CMCuritiba/chamados#163]
A codificação da página já utiliza utf-8, basta atualizar labels como "Servico" para "Serviço", "Patrimonio" para "Patrimônio" e "Descricao" para "Descrição".

Isso está presente na página "Criar chamado", provavelmente em algumas outras páginas que não foram atualizadas.

**Comment by aleodoni** [comment]
@Angelin01, por favor, valide em https://chamados-staging.cmc.pr.gov.br/ e se OK, feche issue.

**Comment by aleodoni** [comment]
Vou fechar a issue. Caso necessário, abrir outra.
