### ISSUE TITLE
Link para chamado no e-mail apontando para o servidor staging

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#165]
Os e-mails automáticos enviados aos usuários sobre o status do chamado estão trazendo o link para o chamado apontando para o staging, p.e.:
https://chamados.staging.cmc.pr.gov.brchamado/detalhe/4/

**Comment by aleodoni** [comment]
@brunosoli , faltou setar a variável de ambiente SERVER_NAME no sistema.
Se não corrigir automaticamente, no próximo restart da aplicação já fica certo. Vou fechar a issue.
