### ISSUE TITLE
Usuários criantes do chamado não conseguem adicionar respostas

### ISSUE THREAD

**Issue by Angelin01** [CMCuritiba/chamados#190]
Não há um botão "Adicionar Resposta" para a pessoa que criou o chamado.

**Comment by aleodoni** [comment]
Não é bug. Foi definido na especificação inicial que não haveria opção para isso.

**Comment by aleodoni** [comment]
Conforme conversa com @brunosoli, essa funcionalidade pode ser adicionada ao sistema.
Para tanto, algumas questões são necessárias : 

1. Hoje, os atendentes não recebem nenhuma notificação de mudança do chamado, pois somente eles  eram responsáveis pelas mesmas. Qual o tipo de notificação que o atendente deverá receber ? (e-mail, notificação visual no sistema...) ?
2. As respostas poderão ser alteradas ? Hoje, o atendente tem essa possibilidade; Acredito que devamos retirar esta opção para que o histórico do chamado fique mais confiável. Concordam ?
3. Quando o solicitante adicionar uma resposta, o mesmo deve receber um e-mail de notificação ?

**Comment by brunosoli** [comment]
A diretoria, os desenvolvedores e a maioria da equipe de atendimento do Suporte não viu necessidade na implementação de respostas por parte dos usuários.

Alguns pontos levantados:
- Evitar uso indevido de respostas (para evitar que vire um chat);
- Simplificar o fluxo de trabalho e utilização do software;
- Dúvidas e questões levantadas em um chamado serão resolvidas por telefone.

A implementação da issue relacionada #196 pode resolver grande parte da confusão que ocorre hoje ao reabrir o chamado (e dependendo da resposta cadastrada no fechamento do chamado).

Se todos estiverem de acordo, esta issue pode ser cancelada.

**Comment by aleodoni** [comment]
Da minha parte, sem problemas. Refinamos então a #196.
@brunosoli, pode fechar essa issue
