### ISSUE TITLE
Atalho para atender chamado

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#192]
Na tela de "Informações do Chamado", é possível adicionar um botão para "Atender" caso o chamado esteja aberto?
Isto permite que o atendente visualize o chamado e assuma-o sem precisar voltar à fila de atendimento para atendê-lo.

**Comment by aleodoni** [comment]
Implementado o botão. Clicando no mesmo, o chamado é atendido pelo atendente e o fluxo volta para a fila. @diemello, @brunosoli, Vejam se este fluxo é o ideal.
