### ISSUE TITLE
Gerenciamento de chamados em setores filhos no organograma

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#193]
A DPSA gostaria de gerir os chamados das áreas sob sua responsabilidade e que utilizam a ferramenta, Setor de Patrimônio e Divisão de Instalações. Outra necessidade é permitir que o Setor de Patrimônio receba e faça a gestão dos chamados abertos para a Divisão de Instalações, visto que toda a gestão administrativa da Divisão será auxiliada pelo Setor.

Esta funcionalidade foi solicitada pelo pessoal do DPSA, deixo-a aqui para discussão e verificação de viabilidade.

**Comment by aleodoni** [comment]
A princípio teríamos que criar no sistema uma amarração entre os setores, ou se essa amarração existir no sistema da elotech, trazê-la de lá. 
@diemello precisamos verificar o citado acima e definir os requisitos necessários.

**Comment by aleodoni** [comment]
@diemello, como existe o campo set_id_superior na view v_setor, é possível fazer o caminho reverso, e habilitar um setor a ver/gerenciar os chamados dos setores "inferiores"
Como já existe no admin o gerenciamento dos setores que recebem chamados, minha sugestão é adicionar opções que permitam a visualização e o gerenciamento dos chamados. Assim, adicionariamos o DPSA no sistema, deixariamos desabilitado a opção dele receber chamados e habilitaríamos a visualização de chamados dos setores "inferiores" a ele.
Isso serviria para todos os outros setores, desde que sigam o organograma.

**Comment by diemello** [comment]
Ótimo, concordo com a solução

**Comment by diemello** [comment]
### Requisito 1 
Criação de uma nova tela (usando template da tela de atendimento)

### Requisito 2
Por se tratar de uma tela para gerenciamento adicionar a coluna **Atendente** 

### Requisito 3
* Criar seletor para setor **Chamados abertos para o setor :** 
* ou uma "tabela" para cada setor que for subordinado ao setor gestor (hoje a DPSA tem 3 setores habilitados abaixo e mais 1 para entrar em funcionamento)
