### ISSUE TITLE
Aspas no texto da resposta

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#194]
Texto com aspas no corpo das respostas aparecem com erro de formatação nos e-mails, por exemplo: `"Suporte"` vira `&quot;Suporte&quot;`

Verificar se não acontece também no corpo dos chamados.

**Comment by aleodoni** [comment]
@brunosoli @diemello correção atualizada no staging. Por favor, validem e me retornem para poder atualizar produção.
