### ISSUE TITLE
Adicionar delay no envio assíncrono de e-mails (cache/redis) e mensagens em lote

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#195]
Verificar se é possível habilitar um _delay_ no envio dos e-mails que permita o acúmulo de mensagens no cache e um envio único com as movimentações ocorridas no chamado.

Exemplo: atendente clica em atender, cadastra uma resposta rápida e fecha o chamado. Se todas as ações ocorrerem dentro de um "_timeout_" definido, as ações são processadas e enviadas em um único e-mail com todas as movimentações, como algo do tipo:
```
...
Status anterior: ABERTO
Novo status: ATENDIMENTO
Nova resposta: "texto da resposta"
Novo status: FECHADO
...
```

**Comment by aleodoni** [comment]
@brunosoli, @diemello 
Sim, é possível fazer isso. Uma ideia seria "agrupar" as respostas dentro de um delay (tipo 10') e só depois manda-las para a fila.
Essa é a maneira mais simples de implementar. Vejam se estão de acordo e me dê o OK para implementarmos.

**Comment by aleodoni** [comment]
@brunosoli, @diemello 
Complementando o comentário anterior, esse agrupamento só pode ser feito através de programação, pois o gerenciador de fila não tem a habilidade de agrupar mensagens; ele apenas gerencia as mesmas.
Então, a solução seria criar uma interface intermediária, e os e-mails seriam enviados à essa interface que aí sim teria o papel de agrupá-los para depois enviá-los para a fila.
Fica ao critério de vocês.
