### ISSUE TITLE
Solicitar descrição na reabertura de chamado

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/chamados#196]
Ao reabrir chamado o sistema deverá solicitar uma descrição/observação sobre a causa reabertura.
Pode funcionar como uma resposta ao chamado, para entrar no histórico.

**Comment by diemello** [comment]
A ideia é tornar obrigatória uma descrição/motivo da reabertura.

**Comment by brunosoli** [comment]
De acordo.
A ideia então é implementar a issue #190 e forçar o usuário a descrever o motivo da reabertura, cadastrando esta descrição como uma resposta no chamado.

**Comment by aleodoni** [comment]
@diemello, @brunosoli O que ficou decidido então. Encerramos essa issue e abrir o sistema para o solicitante poder adicionar respostas também? 
Se for isso, temos que validar as questões que ficaram abertas em #190 e também melhorar a visualização das respostas, pois teremos aí uma conversa entre solicitante e um ou mais atendentes.

**Comment by aleodoni** [comment]
# Descrição
Quando um chamado for reaberto, deverá ser inserido texto com o motivo da reabertura.

## Requisito 1
É obrigatório o cadastro do texto da reabertura.
## Requisito 2
Além do motivo da reabertura, salvar data e hora também.

**Comment by aleodoni** [comment]
@brunosoli, @diemello
O staging já está com a primeira versão que resolve essa issue. Quando puderem dar uma olhada fiquem a vontade.
