### ISSUE TITLE
Criar aviso "Preenchimento obrigatório"

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/chamados#217]
Ao tentar gerar o relatório sem preencher a data cai no 
**Ooops!!! 500
Algo de errado aconteceu!** 

Criar um erro ao lado do campo, poup up ou outra forma para tratar o problema.

**Comment by aleodoni** [comment]
Como o relatório é gerado numa nova página, a validação do campo não pode ser via submit do form.
Teria que ser feita uma validação via javascript antes do form ser submetido.
Ficou mais tranquilo formatar a data de inicio com a data atual. Caso o usuário deixe em branco propositalmente, o sistema automaticamente seta a mesma. Se for digitado qualquer outro valor inválido, o próprio componente ajusta para a data atual.
