### ISSUE TITLE
Transferência de Chamados

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/chamados#225]
# Descrição
Permitir que um chamado possa ser transferido para outro setor. 
## Requisito 1
Chamados poderão ser transferidos apenas para setores setados para tal.
## Requisito 2
Quando um chamado for transferido, seu status (novo status) mudará para TRANSFERIDO
## Requisito 3
Quem transferiu o chamado não terá mais acesso ao mesmo, nem mesmo receberá notificações do mesmo.
## Requisito 4
Caso o chamado tenha sido transferido de maneira errada, o mesmo pode ser devolvido e voltará automaticamente para a fila de chamados do setor que o recebeu inicialmente. Mudar o status (novo status) para DEVOLVIDO ?
## Requisito 5
O restante do fluxo permanece o mesmo

**Comment by aleodoni** [comment]
@brunosoli , @diemello , quando puderem, vejam os requisitos e se quiserem, adicionem/alterem os mesmos ou podemos conversar para refinarmos mais essa issue.

**Comment by aleodoni** [comment]
tinha fechado errado essa issue

**Comment by brunosoli** [comment]
Alguns pontos a se levar em consideração:
- Abuso do recurso: setores com muitas "unidades de tramitação" poderão se perder no fluxo ou passar a utilizar o serviço para outros fins (como o DPSA já vem fazendo);
- Foge do escopo do serviço: controle de chamados e atendimento. Quanto mais simples o software ficar, melhor;
- Filas de atendimento: cada setor terá uma fila de atendimento? Como se dará o controle?
- Treinamento: maior complexidade no módulo admin do sistema, necessitando de treinamento para os usuários responsáveis;
- Procedimento: tudo isto pode ser evitado hoje apenas se definindo claramente o procedimento a se tomar. Por exemplo, um chamado chega para o Suporte, antes de ser escalado para o Dev, o atendente assina o chefe/equipe do Dev, cadastra a resposta ao usuário informando que o chamado foi escalado. O usuário sabe o que está acontecendo e o Dev é notificado por e-mail e o fluxo segue normalmente, tudo isso usando recursos já implementados no sistema.

O objetivo do serviço é o usuário que terá controle e acompanhamento de sua solicitação. Para ele independe como o problema será resolvido internamente, desde que seja sempre atualizado do andamento do chamado.

Pessoalmente vejo muitos pontos negativos e muito fora do escopo. Sugiro cancelar esta issue.

**Comment by diemello** [comment]
Levando em consideração a resposta do @brunosoli 

_Abuso do recurso:_ a sugestão é de cadastrar setor específico para transferência dos chamados levando em consideração apenas setores cadastrados para atender chamados.

_Foge do escopo do serviço:_  ao ser transferido o chamado, o registro de atendimentos fica específico, podendo gerar informações futuras sobre os atendimentos de cada setor além das respostas ficarem mais completa.

_Filas de atendimento:_ o setor que só pode receber chamados de transferência terá uma fila específica.

_Treinamento:_ podemos disponibilizar apenas para os setores que tem necessidade da função, não sendo aberto a todos.

_Procedimento:_ Entendo que a assinatura é interessante para acompanhamento, porém funciona melhor quando o atendente do suporte não precisa ficar com o chamado parado na sua fila, sendo transferida também a responsabilidade pelo atendimento.
