### ISSUE TITLE
Reclassificar chamados

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#232]
Sugestão de melhoria a ser discutida: permitir edição de "Grupo de serviço" e "Serviço" de um chamado em aberto.

**Muitas** vezes os usuários criam chamados com a classificação errada ou não se preocupam em preenchê-la corretamente. Para facilitar o trâmite (evitando forçar que o usuário reabra o chamado), o atendente poderia editar "Grupo de serviço" e "Serviço" após assumir um chamado.

Qual é a interface padrão do _framework_ para este tipo de edição? É possível fazê-lo _inline_?

**Comment by aleodoni** [comment]
@brunosoli, a interface padrão é o [bootstrap](https://getbootstrap.com/docs/4.0/getting-started/introduction/). 
Pode ser feito inline a partir de programação que busque os serviços, grupos de serviço e disponibilize para a alteração. 
Lógico que isso implica em outras alterações no sistema que podemos conversar para depois refinarmos a issue.
