### ISSUE TITLE
Tela de Informações do Chamado não exibe os campos localização e pavimento

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#238]
## Descrição

**Precondições**
- Chamado aberto para setor com os campos Localização e Pavimento habilitados.

**Passos para reproduzir**
- Abrir um chamado para algum setor com os campos Localização e Pavimento habilitados, por exemplo, DPSA;
- Logar como atendente no setor de destino do chamado, por exemplo, DPSA;
- Visualizar o chamado recém aberto.

**Comportamento atual**
- Os campos Localização e Pavimento não são exibidos na tela de Informações do Chamado.

**Comportamento esperado**
- Se o chamado foi aberto com informações de Localização e Pavimento, estes campos devem ser exibidos na tela de Informações do Chamado, tanto para atendentes quanto para o criador do chamado.

**Comment by aleodoni** [comment]
@brunosoli, as informações citadas acima foram adicionadas nas telas de detalhes do chamado (usuário), e atendente e também na impressão do chamado.
Já está disponível para validação no staging e fico no aguardo do OK para colocarmos em produção.

**Comment by aleodoni** [comment]
@brunosoli, complementando : Para testar, criei o chamado 57 para o setor de suporte com os campos Patrimônio, Localização e Pavimento preenchidos.
