### ISSUE TITLE
Exibir quantidade de chamados no setor

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#245]
**Descrição**
Para avaliação: sugere-se que o número de chamados abertos/atendimento/fechados de cada fila sejam exibidos para todos os usuários. O objetivo é aumentar a transparência e melhorar o _feedback_ do sistema para o usuário.

**Requisito**
Ao criar um chamado, quando o usuário selecionar o setor (fila) desejado, os _labels_ que são exibidos hoje na tela de atendimento são similarmente exibidos na tela de criação do chamado. Os labels, respectivamente em verde, amarelo e vermelho, são:
"Total de chamados finalizados : X"
"Total de chamados em atendimento : Y"
"Total de chamados abertos : Z"

Sugestão: os _labels_ podem aparecer abaixo do _header_ "Chamados".

**Contexto adicional**
Os _labels_ podem ser exibidos similar ao já utilizado:
![qtd-chamados](https://user-images.githubusercontent.com/7805168/57408658-9f2fa180-71bc-11e9-8f99-fbef5c1500e5.png)

**Comment by diemello** [comment]
Sugiro que a informação seja exibida somente no momento da criação do chamado junto a informação de "**Chamado criado co sucesso. O tempo...**" que será alterada pela issue #246 

![image](https://user-images.githubusercontent.com/18293096/57455099-c4fe8a00-7240-11e9-8bbd-60bbdb91ebd9.png)
