### ISSUE TITLE
Tempo estimado de atendimento

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#246]
**Descrição**
Informar ao usuário, baseado na média de tempo em que chamados de determinado serviço são resolvidos, o tempo estimado para resolução do chamado recém aberto.

**Requisito 1**
- Usuário cria o chamado normalmente;
- Quando o usuário clica em "Salvar", a mensagem "Chamado criado com sucesso" deve conter o tempo estimado de atendimento.

**Requisito 2**
O texto poderia ficar, por exemplo: "Chamado criado com sucesso. O tempo estimado de atendimento é de **01 dias, 23h e 45m**."

A mensagem pode ser exibida no campo já existente:
![tempo-atendimento](https://user-images.githubusercontent.com/7805168/57409902-cfc50a80-71bf-11e9-8caf-ff12ed1694f5.png)

E é importante que a mensagem não esmaeça (fique na tela até que o usuário navegue para outra página).

**Requisito 3**
Estudar a melhor forma de manter e atualizar as estatísticas de tempo.

**Comment by ewerton70** [comment]
Penso que informar 'Tempo médio de atendimento' seria melhor que 'Tempo estimado de atendimento', pois o segundo soa ao usuário como o tempo que o suporte está estimando para atendê-lo, e o primeiro não gera compromisso ao suporte.

**Comment by brunosoli** [comment]
Considerando a _issue_ #244, a mensagem pode ser exibida por notificação _push_.

O lado ruim é que o usuário tem que primeiramente permitir os _pop-ups_ no _browser_. Mas é possível também exibir a informação no _banner_ **e** no _pop-up_.

**Comment by rodrigoferraro** [comment]
Nesta fase inicial de mudanças, para não correr o risco de dar uma estimativa falha, para a pessoa errada, no momento errado (porque sabemos que isso irá acontecer)... se não tiver profissional disponível para atender ao chamado na hora, sugiro que tenha alguém responsável por ligar ao cliente assim que o chamado pipocar na fila, para "confortá-lo", e assegurá-lo que em breve ele será atendido.

**Comment by rodrigoferraro** [comment]
> Penso que informar 'Tempo médio de atendimento' seria melhor que 'Tempo estimado de atendimento', pois o segundo soa ao usuário como o tempo que o suporte está estimando para atendê-lo, e o primeiro não gera compromisso ao suporte.

acho que é realmente isso que devemos buscar, "gerar compromisso".. e honrar com ele... conquistando assim, confiança, e relação de parceria.

**Comment by rodrigoferraro** [comment]
> Nesta fase inicial de mudanças, para não correr o risco de dar uma estimativa falha, para a pessoa errada, no momento errado (porque sabemos que isso irá acontecer)... se não tiver profissional disponível para atender ao chamado na hora, sugiro que tenha alguém responsável por ligar ao cliente assim que o chamado pipocar na fila, para "confortá-lo", e assegurá-lo que em breve ele será atendido.

então feito piazada... não vou excluir pra não perder o histórico de idiotice.. mas desculpe pelo tumulto criado.
