### ISSUE TITLE
Limite de tempo para reabertura de chamado

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#247]
**Problema**
O aplicativo permite aos usuários reabrir chamados antigos, promovendo mau uso da ferramenta.

**Sugestão**
Um chamado só pode ser reaberto se foi fechado há menos de um tempo definido. Discutir o tempo: sugestão 1 mês.

**Descreva as alternativas que você considerou**
- Da forma como está hoje, o usuário reaproveita um chamado antigo para resolver um novo problema do mesmo tipo. Isto gera estatística inconsistente.
- Os atendentes poderão reabrir a qualquer momento? Discutir isto.

**Comment by diemello** [comment]
Sugestão de tempo 1 semana
