### ISSUE TITLE
Anexos nos chamados

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/chamados#249]
Não á possível adicionar **pdf** como anexo do chamado

**Descreva a solução que você gostaria**
Adicionar a opção de anexar pdf e talvez outros tipos de arquivos

**Contexto adicional**
Hoje o sistema permite anexar apenas arquivos "jpg, png, gif, jpeg".

**Comment by DePorto** [comment]
@aleodoni basta então modificar o filtro para permitir .pdf

**Comment by aleodoni** [comment]
Trabalhando nessa issue

**Comment by aleodoni** [comment]
Analisando o código, as mudanças para que o sistema aceite PDF's no campo não serão apenas a mudança do filtro, pois o tipo de campo usado no modelo é ```ImageField``` que aceita apenas imagens;
Temos 2 opções : 
1. Alterar o campo ```ImageField``` para ```FileField```; ainda preciso verificar se essa alteração não acarreta nenhum tipo de erro na hora de rodar as migrações para alterar a tabela no BD;
2. Criar outro campo para anexar PDF's; esta opção não afetaria nada em relação às migrações, mas não gosto dela porque poderia confundir o usuário na hora de fazer o upload de arquivo.
Acho que seria legal a gente discutir um pouco melhor essa issue e depois definirmos a solução em comum.

**Comment by aleodoni** [comment]
Atualizando: Testei localmente trocar o tipo de campo de ```ImageField``` para ```FileField``` e rodei as migrations. Sem problema. Não foi alterado nada no BD; provavelmente apenas foi retirada a validação para tipo de arquivo (somente imagem).
Então, podemos utilizar a opção 1 citada anteriormente. Vou só implementar as validações para filtro de tipo de arquivo e testar.

**Comment by aleodoni** [comment]
@diemello @DePorto 
Implementado e disponível para validação no https://chamados-staging.cmc.pr.gov.br/
Fechando a bagaça

**Comment by diemello** [comment]
falta testar, mas aparentemente já está pronto pra colocar em produção

**Comment by aleodoni** [comment]
@diemello, @DePorto  Em produção. Vou fechar esta issue, caso necessite abrimos uma nova de bug
