### ISSUE TITLE
Erro ao acessar a página de lista de chamados para atendimento

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/chamados#253]
**Descreva o bug**
Ao acessar a lista de chamados, o carregamento está lento e aparecem mensagens de erro. (mensagem e/ou erro 500)

**Para Reproduzir**
Passos para reproduzir o comportamento :
1. Vá até https://chamados.cmc.pr.gov.br
2. Clique em 'Atendimento'
3. Demora no carregamento da página e mensagem de erro:
  - Erro 500
  - Mensagem: "Object
certisignerconf.js:4 A div certisigner-enabled nao foi encontrada.
/fila/lista_parceiros.html:1 Failed to load resource: the server responded with a status of 404 (Not Found)"

**Comportamento Esperado**
Carregar a lista de chamados para serem atendidos.

**Comment by aleodoni** [comment]
@DePorto Resetei a aplicação. Agora está ok.
Em relação à lentidão, teria que alterar o código para limitar a busca de chamados (por exemplo, retornar os últimos 50)

**Comment by diemello** [comment]
já estava sendo tratado pela issue #241 ??

**Comment by aleodoni** [comment]
@diemello, @DePorto  Em produção. Vou fechar esta issue, caso necessite abrimos uma nova de bug
