### ISSUE TITLE
Migração de dados conforme modificações no organograma

### ISSUE THREAD

**Issue by DePorto** [CMCuritiba/chamados#260]
**A sua melhoria está relacionada com um problema ? Por favor descreva.**
Houve a extinção de duas áreas do organograma da CMC. É preciso realocar os chamados para outras áreas (IDs)

**Descreva a solução que você gostaria**
 1. migração dos chamados da extinta Seção de Telefonia para a Divisão de Suporte;
 
 2. migração dos chamados do extinto Setor de Serviços Gerais, pois criaram a Divisão de Serviços Gerais com novo ID

**Comment by aleodoni** [comment]
> **A sua melhoria está relacionada com um problema ? Por favor descreva.**
> Houve a extinção de duas áreas do organograma da CMC. É preciso realocar os chamados para outras áreas (IDs)
> 
> **Descreva a solução que você gostaria**
> 
> 1. migração dos chamados da extinta Seção de Telefonia para a Divisão de Suporte;
> 2. migração dos chamados do extinto Setor de Serviços Gerais, pois criaram a Divisão de Serviços Gerais com novo ID

@DePorto, algumas dúvidas:

1. Essa migração é apenas mudar o id dos chamados de um setor para outro ? Acredito que não, pois os grupos de serviço e serviços estão relacionados com o setor e sendo assim, seria necessário fazer um mapeamento de-para em 2 níveis; 
2. Os novos setores já foram criados ? 
3. Ainda estão abrindo chamados para esses 2 setores que irão ser desativados?
4. Como você pensa nesse processo ? Criar um script para ser rodado ou executar um sql direto ?

De qualquer maneira, irei precisar de : 
1. Dump do banco de dados para que eu possa rodar localmente e testar o processo;
2. Tempo para relembrar a estrutura do sistema, pois faz um bom tempo que não leio o código haja visto que o mesmo iria ser substituído por outro software.
3. Também terei que criar uma parte da estrutura do ambiente aqui na minha máquina; espero que não precise alterar o código, pois isso vai complicar bastante o processo.

Adianto que dependendo da "migração" que vocês desejam fazer, o processo é muito complicado.

**Comment by aleodoni** [comment]
Complementando o comentário anterior, dei uma analisada e a alternativa mais viável seria atualizar os grupos de serviços e serviços que possuem o código do setor que foi extinto para o código do setor criado e depois atualizar também todos os chamados para o código do setor criado.
Mesmo assim, essa solução não garante que algum erro possa ocorrer e gerar inconsistência na base de dados; teríamos que testar essa solução e validar os resultados; esta última etapa sendo a mais demorada.

**Comment by DePorto** [comment]
@aleodoni , o que a equipe de arquitetura de serviços vai providenciar é novo sistema de chamados, não havendo necessidade de se realizar esta demanda, nestes termos. Agradeço a atenção, mas vamos livrar esta demanda. Talvez haja necessidade de alguma consulta a você referente à estrutura na migração das informações para o novo sistema,

**Comment by aleodoni** [comment]
> @aleodoni , o que a equipe de arquitetura de serviços vai providenciar é novo sistema de chamados, não havendo necessidade de se realizar esta demanda, nestes termos. Agradeço a atenção, mas vamos livrar esta demanda. Talvez haja necessidade de alguma consulta a você referente à estrutura na migração das informações para o novo sistema,

Sem problemas, fico à disposição.
