### ISSUE TITLE
Migração dos chamados atuais para Zammad

### ISSUE THREAD

**Issue by ewerton-dif** [CMCuritiba/chamados#261]
- [x] estudar e definir como migrar
- [x] criar script para criação de tickets no Zammad
- [x] definir integração dos campos/dados com Zammad
- [x] criar script para pegar dados do Chamados e criar tickets no Zammad
    - [x] incluir 'localização de execução do serviço' na descrição do problema
    - [x] adicionar área de lotação do usuário na descrição
    - [x] migrar anexos (ticket_articles em base64)
    - [x] aceitar data de criação/fechamento no formato Zammad (converter formato e timezone)
    - [x] criar logs em arquivo
    - [x] desativar envio de e-mail na migração
    - [x] teste em base quente
    - [x] corrigir campo proprietário e detalhes adicionais
    - [x] arrumar detalhes depois da 1ª importação no zammad produção
    - [x] fechar campos abertos/em atendimento com mais de 3 meses
    - [x] apagar os mais de 3.700 importados em produção, atualizar .CSV e realizar novas importações

**Comment by ewerton-dif** [comment]
Abri estas issue para confirmar algumas informações do Zammad, que Carlão e Bruno estão realizando.
Pelo que vi na migração, em GRUPO deve-se ter os prestadores de serviços dos chamados, sendo alguns deles DTIC, Serviços Gerais, etc.
Em ORGANIZAÇÃO, como somos só CMC, poderíamos usar como a área do usuário/cliente, tipo Contabilidade, RH, Projuris, etc, mas teria que migrar do LDAP ou cadastrar na mão.

**Comment by ewerton-dif** [comment]
Vocês conseguiram migrar ou acessar todos os usuários/e-mails pelo Zammad?

**Comment by brunosoli** [comment]
> Vocês conseguiram migrar ou acessar todos os usuários/e-mails pelo Zammad?

Os usuários sim, na minha base de teste. Aproveito hoje que vou dar manutenção no LDAP e deixo a árvore pronta pra importar e testar o zammad com o LDAP de produção.
E-mail e integração com IMAP também funcionam.

**Comment by cpinheiro26** [comment]
Os grupos são os setores mesmo como mencionou @ewerton-dif , quanto ao chamado em si existem basicamente dois campos "Assunto" e "Descrição" e o proprietário do chamado aberto é setado selecionando um dos usuários cadastrados como atendente / admin no Zammad.

Meu servidor teste tb importei os usuário do LDAP teste sem problemas.

**Comment by ewerton-dif** [comment]
Quando fui em Configurações / Sistema / Integrações / LDAP, depois de sincronizar a aprece a mensagem:
LDAP usuário para Zammad usuário (500/500):
Usuários: 0 criado, 0 atualizado, 0 intocado, 500 Pulado, 0 falhou, 0 desativado
e não aparecem os usuários para mim :(

**Comment by ewerton-dif** [comment]
Os usuários são trazidos automaticamente com a configuração do LDAP, ou tem que fazer a importação? Como fazer pelo LDAP? pois só vi a importação por .csv

**Comment by brunosoli** [comment]
São trazidos automaticamente, só mapear o LDAP e boa. O problema que estava tendo antes era de configurar esse mapeamento, mas deletei a subárvore `ou=Computadores` e deu bom.
Se cê conseguir apontar seu zammad local pro tauari que deve funcionar.
Eu usei o filtro: `(&(objectclass=inetOrgPerson)(employeeNumber=*))`

**Comment by ewerton-dif** [comment]
Quando vamos atender um chamado (atual), aparece o nome do usuário e o SETOR a que ele pertence. Quem faz esta ligação? O sistema de chamados pega pelo sistema de RH? Qual a ideia pelo Zammad?

**Comment by brunosoli** [comment]
É informação útil para relatório, mas não é indispensável.
@cpinheiro26 vai saber melhor, mas aparentemente o zammad não categoriza usuários (me parece que apenas por grupos de atendentes ou organizações).
Podemos categorizar de forma macro por tags (por diretorias rh, contab, dtic, daf), apenas pra não perder a informação. Que tal?

**Comment by ewerton-dif** [comment]
Dá para usar a ORGANIZAÇÃO, mas em algum momento o zammad precisa fazer a relação usuario -> área... daí porque estou perguntando como o 'chamados' obteve isto.

**Comment by ewerton-dif** [comment]
Precisarei também o .CSV do cadastro dos usuários, que não tenho... Bruno, vc poderia fazer o favor de me enviar?
Inclusive, quem sabe lá tem esta relação usuário x área mais claro.

**Comment by ewerton-dif** [comment]
Também tem o ATENDENTE do chamado, que no zammad é o PROPRIETÁRIO do ticket... penso que é o usuario_id que está em core_chamadoresposta... é isto? Daí também precisarei deste .CSV (que acho ser o mesmo dos usuários solicitantes do chamado)

**Comment by ewerton-dif** [comment]
Outra coisa... as pessoas que são ATENDENTES dos chamados, dos vários setores, também é preciso saber quem são, configurar isto no zammad, para daí migrar o campo atendente->proprietário corretamente... senão o zammad dará erro e não conseguiremos saber quem realizou os atendimentos :(

**Comment by cpinheiro26** [comment]
> É informação útil para relatório, mas não é indispensável.
> @cpinheiro26 vai saber melhor, mas aparentemente o zammad não categoriza usuários (me parece que apenas por grupos de atendentes ou organizações).
> Podemos categorizar de forma macro por tags (por diretorias rh, contab, dtic, daf), apenas pra não perder a informação. Que tal?

Sim, ele trata apenas como "grupos" que no nosso caso são os setores da CMC

**Comment by cpinheiro26** [comment]
> Outra coisa... as pessoas que são ATENDENTES dos chamados, dos vários setores, também é preciso saber quem são, configurar isto no zammad, para daí migrar o campo atendente->proprietário corretamente... senão o zammad dará erro e não conseguiremos saber quem realizou os atendimentos :(

O Zammad trata "Agente" como categoria de quem pode ver / interagir com chamados porém não seta automaticamente como "proprietário", o proprietário precisa ser definido manualmente no chamado (dizendo a respeito dos novos abertos pelo Zammad)  e este mesmo proprietário já tem de estar setado com o parâmetro "Agente" e com uma conta de e-mail atribuída ao mesmo pois do contrário ele não deixa o "Agente" ser setado como proprietário. É bem confuso precisaremos nos adaptar

**Comment by ewerton-dif** [comment]
Uma das pendências no Sprint 24/08 é "Verificar numeração dos chamados importados"... então, como o Zammad segue uma ordem de numeração, penso que deveríamos considerar termos números de chamados/tickets diferentes do sistema de chamados atual... ou seja, usar o novo número que o Zammad criar. O que acham?

**Comment by brunosoli** [comment]
O zammad tem umas regras que podemos usar. A padrão é ID + número do ticket.
Podemos definir o ID do sistema como, digamos, 10 e usar o mesmo número do ticket no sistema antigo. O chamado 318 vira 10318.
Que tal?

**Comment by ewerton-dif** [comment]
Vou fazer uns testes e depois de falo.

**Comment by ewerton-dif** [comment]
Fiz o seguinte teste: em administração (engrenagem lado esquerdo em baixo) / sistema / objetos, criei o 'Ramal'. Quando crio um novo ticket, aparece o campo Ramal para ser preenchido como obrigatório. Nos tickets já criados anteriormente, ao fazer qualquer alteração (ex. status Fechado), ele pede o Ramal (embaixo de prioridade e estado, do lado direito). E cria o campo certinho lá na base de dados!! ticket.ramal
Dá para usar assim se vocês quiserem... daí eu migrarei o ramal para o campo específico.

**Comment by brunosoli** [comment]
Puts, comemos bola Ews, desculpe.
Semana passada conversamos com o Tarcísio e decidimos fazer a gestão dos ramais no LDAP. Fazendo isso o usuário nem precisa digitar o ramal dele.

Quando for conveniente informar outros telefones ou meios de contato, pode ser no corpo do ticket.

**Comment by ewerton-dif** [comment]
No zammad.cmc.pr.gov.br, foi utilizado o ID do sistema = 98, ou seja, os números dos tickets começariam em 98.000.
Temos 3.751 chamados antigos a serem migrados, indo os próximos números para 101.752 em diante.
Como só temos uma organização/entidade, porque não começar com um número mais baixo e redondo, tipo 10.000 ou 20.000?

**Comment by ewerton-dif** [comment]
Nos chamados antigos, além do setor_solicitante (área do usuário que abriu o chamado) e do setor_id (setor que irá atender o chamado), tem um campo localizacao_id que de vez em quando tem números baixos (acho que de 1 a 6) somente quando setor_id = Patrimônio OU setor_id = Manutenção e Reforma... alguém sabe do que se trata, e se deve ser migrado?
