### ISSUE TITLE
Anexar arquivos

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#76]
O usuário poderá fazer upload de arquivo, por exemplo, uma foto do problema.
Pensar sobre filtragem de tipos de arquivos permitidos e tamanho máximo.

Não é urgente e não é necessário para a versão 1.0.

**Comment by aleodoni** [comment]
:+1:

**Comment by aleodoni** [comment]
# Requisitos

## Requisito 1
Usuário pode anexar 1..n arquivos

## Requisito 2
Qualquer tipo de arquivo, exceto:
- Vídeo
- Áudio

## Requisito 3
Tamanho máximo: 10M

**Comment by aleodoni** [comment]
Um bom ponto de partida é seguir este demo : 
https://simpleisbetterthancomplex.com/tutorial/2016/11/22/django-multiple-file-upload-using-ajax.html

**Comment by aleodoni** [comment]
Fechando issue. Se precisar, criamos outras de bug.
