### ISSUE TITLE
Relatórios

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/chamados#85]
Todos deverão ser emitidos por período e exibindo todos os dados do chamado
Criar opção para selecionar por Grupo de Serviços
Criar opção para selecionar por Setor Solicitante
Criar opção para selecionar por Status

**Comment by aleodoni** [comment]
Conforme conversa com @diemello e @brunosoli, vamos testar o pacote https://github.com/alexmorozov/templated-docs

Esse pacote precisa do libreoffice para rodar.

Para não detonar o staging, vou realizar instalação do "core" do libreoffice numa máquina virtual e verificar se a aplicação funciona.

**Comment by aleodoni** [comment]
Testado numa máquina rodando Debian 9 sem interface gráfica.
Usei um template .odt para gerar um arquivo .pdf
Funcionou.
Instalei libreoffice-core e libreoffice-writer
Esses 2 pacotes instalam apenas bibliotecas(libs). Acredito que seja uma boa solução para gerarmos documentos no python/django
@diemello @brunosoli 
Fico no aguardo para conversarmos e implementarmos solução no staging.

**Comment by diemello** [comment]
Segue modelo de relatório. deem suas opniões! @aleodoni @brunosoli 
Se for possível criar zebrado, acredito ser mais vizual.

O Git não deixou adicionar o .odt
[modelo_relatorio_chamados.docx](https://github.com/CMCuritiba/chamados/files/1825161/modelo_relatorio_chamados.docx)

**Comment by aleodoni** [comment]
# Requisito 1
Deverá ser informado o período (data de início e data de fim). Data de início pode ser deixada em branco, nesse caso, o sistema pegará a data atual.

# Requisito 2
Poderá ser selecionado o setor para qual os chamados foram direcionados. Se for deixado em branco, selecionará todos os setores.

# Requisito 3
Poderá ser selecionado o grupo de serviço dos chamados. Se for deixado em branco, selecionará todos os setores.

# Requisito 4
Deverá gerar arquivo para download no formato PDF

# Requisito 5
Deverá existir quebra por setor para o qual os chamados foram abertos. No final de cada setor, emitir total de chamados.

# Requisito 6
Os chamados deverão ser separados por linha e, se possível, zebrado.

@diemello por favor, verifique se os requisitos estão ok.

**Comment by brunosoli** [comment]
[modelo-relatorio-chamados.odt.tar.gz](https://github.com/CMCuritiba/chamados/files/1826665/modelo-relatorio-chamados.odt.tar.gz)

**Comment by aleodoni** [comment]
Primeira versão do relatório implementada. @diemello @brunosoli por favor verifiquem se está ok.

**Comment by aleodoni** [comment]
[relatorio_chamados.pdf](https://github.com/CMCuritiba/chamados/files/1833369/relatorio_chamados.pdf)

Criei também uma versão retrato para o relatório @diemello @brunosoli

**Comment by diemello** [comment]
Revisados os relatórios e por mim estão Ok
@aleodoni Favor verificar filtro por Status.

**Comment by aleodoni** [comment]
Vou fechar a issue. Correções, etc, abrir issue de bug.
