### ISSUE TITLE
Responsividade Celular

### ISSUE THREAD

**Issue by diemello** [CMCuritiba/chamados#88]
Verificar responsividade pois em teste no firefox e no chrome a lista de chamados ficou fora da tela.
![responsividade celular](https://user-images.githubusercontent.com/18293096/33661672-1e0bbb3c-da70-11e7-84f2-879ddb39fc3b.png)

**Comment by aleodoni** [comment]
Para resolver este problema, temos 2 soluções possíveis : 

1. Eliminar a tabela (datatables)

2. Diminuir a quantidade de elementos na tabela, para que a mesma caiba no espaço.

O sistema já está implementado usando um framework responsivo (bootstrap).
