### ISSUE TITLE
Configurar sockets

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#93]
Ao reiniciar o servidor, os sockets criados em /var/run/webapps/{aplicacao} são deletados automaticamente pelo SO.
O /var/run é o caminho correto para utilizar os sockets mas nós devemos garantir que os sockets sejam criados toda vez que a aplicação for lançada.

**Comment by aleodoni** [comment]
@brunosoli, vou fechar essa issue. Já resolvemos, bl?
