### ISSUE TITLE
Filtro na listagem de serviços

### ISSUE THREAD

**Issue by brunosoli** [CMCuritiba/chamados#95]
O filtro por grupos de serviços na tela de serviços não é aplicado corretamente após criar um novo serviço para um grupo.

Para reproduzir: como administrador/gerente, ao acessar Cadastro / Serviços / selecionar um grupo, clicar em Novo, criar um novo serviço e clicar em Salvar. Após a criação, a listagem aparece com todos os serviços disponíveis ao invés de listar apenas do grupo selecionado no combobox.

**Comment by aleodoni** [comment]
@brunosoli, verifiquei o problema e na verdade está faltando um componente visual nos servidores. Se vc reparar, a combo dos setores não está com o layout do bootstrap. por isso que acontece o problema. Como não tem alteração no código, vou corrigir o problema nos servidores e fechar a issue.
